# fly.toml app configuration file generated for delicate-hill-866 on 2023-06-14T00:22:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "delicate-hill-866"
primary_region = "nrt"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
